# Generated by Django 4.0.4 on 2022-10-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CorrectOption',
        ),
    ]
