# Generated by Django 4.1.2 on 2022-11-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0003_alter_questionoption_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="photo",
            field=models.ImageField(
                default="photos/default_pic.svg",
                upload_to="photos/",
                verbose_name="Photo",
            ),
        ),
    ]
