# Generated by Django 4.1.2 on 2022-11-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0004_alter_newuser_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="photo",
            field=models.ImageField(
                default="photos/default_pic.png",
                upload_to="photos/",
                verbose_name="Photo",
            ),
        ),
    ]
