# Generated by Django 4.1.2 on 2022-11-10 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0006_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
